export const ATTACKS = [
  {
    id: "FIREBALL",
    title: "Fireball",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Fire",
    description: "A blazing projectile that scorches enemies on impact.",
  },
  {
    id: "INFERNO",
    title: "Inferno",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Fire",
    description: "Unleashes a raging inferno that engulfs everything in flames.",
  },
  {
    id: "LIGHTNING",
    title: "Lightning",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Electric",
    description: "A lightning strike that hits instantly with electrifying force.",
  },
  {
    id: "TSUNAMI",
    title: "Tsunami",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Water",
    description: "A massive wave crashes over opponents, overwhelming them.",
  },
  {
    id: "TORNADO",
    title: "Tornado",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Wind",
    description: "A violent whirlwind that lifts and tosses enemies around.",
  },
  {
    id: "PUNCH",
    title: "Punch",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Physical",
    description: "A quick and reliable strike when magic isn’t enough.",
  },
  {
    id: "ICE_SPIKES",
    title: "Ice Spikes",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Ice",
    description: "Sharp spikes of ice erupt from the ground beneath the enemy.",
  },
  {
    id: "BLIZZARD",
    title: "Blizzard",
    image: "/images/wizard/attack.png",
    baseDamage: 100,
    element: "Ice",
    description: "A freezing storm that batters enemies with snow and ice.",
  },
];