export const WIZARDS = [
  {
    id: "ATTACKWIZARD",
    title: "Attack Wizard",
    description: "Unleashes devastating damage but has very low health.",
    image: "/images/wizards/attack.png",
    spriteWidth: 64,
    spriteHeight: 64,
    animation_speed: 120,
    selection_sheet: "/images/wizards/attack_attack.png", // Reusing attack sprite for selection
    selection_frames: 12,
    idle_sheet: "/images/wizards/attack_idle.png",
    idle_frames: 5,
    attack_sheet: "/images/wizards/attack_attack.png",
    attack_frames: 12,
    death_sheet: "/images/wizards/attack_death.png",
    death_frames: 13,
  },
  {
    id: "TANKWIZARD",
    title: "Tank Wizard",
    description: "With a massive health pool but reduced damage, they stand firm against any onslaught.",
    image: "/images/wizards/tank.png",
    spriteWidth: 64,
    spriteHeight: 64,
    animation_speed: 120,
    selection_sheet: "/images/wizards/tank_selection.png",
    selection_frames: 10,
    idle_sheet: "/images/wizards/tank_idle.png",
    idle_frames: 5,
    attack_sheet: "/images/wizards/tank_attack.png",
    attack_frames: 12,
    death_sheet: "/images/wizards/tank_death.png",
    death_frames: 13,
  },
  {
    id: "BALANCEDWIZARD",
    title: "Balanced Wizard",
    description: "A perfect blend of offensive power and durability.",
    image: "/images/wizards/balanced.png",
    spriteWidth: 64,
    spriteHeight: 64,
    animation_speed: 120,
    selection_sheet: "/images/wizards/balanced_idle.png", // Reusing idle sprite for selection
    selection_frames: 5,
    idle_sheet: "/images/wizards/balanced_idle.png",
    idle_frames: 5,
    attack_sheet: "/images/wizards/balanced_attack.png",
    attack_frames: 12,
    death_sheet: "/images/wizards/balanced_death.png",
    death_frames: 13,
  },
  {
    id: "GAMBLERWIZARD",
    title: "Gambling Wizard",
    description: "With random health and damage, every battle is a high-stakes risk.",
    image: "/images/wizards/gambler.png",
    spriteWidth: 64,
    spriteHeight: 64,
    animation_speed: 120,
    selection_sheet: "/images/wizards/gambler_selection.png",
    selection_frames: 5,
    idle_sheet: "/images/wizards/gambler_idle.png",
    idle_frames: 5,
    attack_sheet: "/images/wizards/gambler_attack.png",
    attack_frames: 12,
    death_sheet: "/images/wizards/gambler_death.png",
    death_frames: 13,
  },
];
;